version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: alex_koin:latest
    env_file:
      - config/docker.env
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:9.6.3
    env_file:
      - config/docker.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
